version: "3.9"
services:
  postgresMarket:
    container_name: postgresMarket
    image: postgres
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "MarketBot_ifw8e9238f0sd0j9eur029u3fj09we8jfsedf0s9ew0e9"
      POSTGRES_USER: "postgresPavel"
      POSTGRES_PASSWORD: "postgresPavelTest"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./datainit:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgresPavel -d MarketBot_ifw8e9238f0sd0j9eur029u3fj09we8jfsedf0s9ew0e9" ]
      #означает тест на готовность базы данных minsport от пользователя postgresPavel.
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
    networks:
      - postgresMarket


  pgadminMarket:
    container_name: pgadminMarket
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "koraginp@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "postgresPavelTest"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
    networks:
      - postgresMarket

  postgres_exporter:
    container_name: exporter_container
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_URI: "postgres:5432/MarketBot_ifw8e9238f0sd0j9eur029u3fj09we8jfsedf0s9ew0e9?sslmode=disable"
      DATA_SOURCE_USER: "postgresPavel"
      DATA_SOURCE_PASS: "postgresPavelTest"
      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres_exporter/queries.yaml"
    volumes:
      - ./data:/etc/postgres_exporter/queries.yaml:ro
    ports:
      - "9187:9187"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 500M
    networks:
      - postgresMarket

#volumes:
#  data:
#  pgadmin-data:

networks:
  postgresMarket:
    driver: bridge
