version: 1
disable_existing_loggers: True

formatters:
  default:
    format: '[%(asctime)s] #%(levelname)-8s %(filename)s: %(lineno)d - %(name)s - %(message)s'

  formatter_1:
    format: '[%(asctime)s] #%(levelname)-8s %(filename)s: %(lineno)d - %(name)s - %(message)s'

filters:
  vse_filter:
    (): error.log_files.DebugFilter

handlers:
  default:
    class: logging.StreamHandler
    formatter: default
    level: DEBUG
    filters: [vse_filter]

  error_file:
    class: logging.FileHandler
    filename: logs.log
    mode: w
    level: DEBUG
    formatter: formatter_1
    filters: [vse_filter]

loggers:
  main:
    level: DEBUG
    handlers: [default]

root:
  formatter: default
  handlers: [default]


